RESTurant/config/routes.rb
Rails.application.routes.draw do

  root to: 'users#login'
  resources :users, only: [:new, :create, :show, :destroy]
  resources :parties
  resources :customers 
  resources :orders
  resources :foods

  get 'sessions/new' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  delete 'sessions' => 'sessions#destroy'
  get 'login' => 'users#login'

end

RESTurant/app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :party
  has_many :orders, dependent: :destroy
  has_many :foods, :through => :orders    # NECESSARY??

  validates :name, presence: true
  # after_create :update_total        # used to update customer total after adding/removing food orders

  def add_customer
    # add new customer to table
  end

  def add_order
    # adds food + customer_id to orders 
    # if pair exists, inc quantity by 1
    # update customer_id total
  end

  def update_total
    # how to update customer total after adding/removing an order???
  end

end

RESTurant/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate

  def index
    @customers = Customer.all
  end
  
  def show
    @customer = Customer.find(params[:id])
    @orders = @customer.orders.all            # selects all orders with this @customer_id
    @foods = @customer.foods.all
    # render plain: @orders.inspect
  end

  def new
    @customer = Customer.new
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end

  def create
    @customer = Customer.create(customer_params)

    if @customer.save
      redirect_to customer_path(@customer)            # "customer#show" profile view    redirect_to @customer ??
    else 
      render 'new'      # otherwise, go back to new form
    end
  end
  
  def update
    @customer = Customer.find(params[:id])

    if @customer.update(customer_params)
      redirect_to customer_path(@customer)            # "customer#show" profile view    redirect_to @customer ??
    else
      render 'edit'     # otherwise, go back to edit form
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to customers_path                  # "customers#index" list of all customers view
  end

  private   # strong params
  def customer_params
    params.require(:customer).permit(:name)     # include :total, :party_id ???
  end

end

RESTurant/app/views/customers/_customer.html.erb
<!-- Shows each customer in a table row -->
<tr>
  <td><%= customer.name %></td>
  <td>$<%= customer.total %></td>
  <td><%= link_to 'View', customer_path(customer) %></td>
  <td><%= link_to 'Delete', customer_path(customer),
          method: :delete, 
          data: {confirm: 'You sure about that, big guy?'} %></td>
</tr>

RESTurant/app/views/customers/_form.html.erb
<!-- EDIT:  <%= form_for :customer, url: customer_path(@customer), method: :patch do |f| %> -->
<%= form_for @customer do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br><br>

  <!-- <%= link_to Add Order, new_order_path %> CAN I PUT THIS HERE??? -->
  <%= f.submit %><br>
<% end %>

RESTurant/app/views/customers/edit.html.erb
<div class="form">
  <h1>Edit Customer Info</h1>
  <%= render partial: 'form' %>
</div>

RESTurant/app/views/customers/index.html.erb
<button>
  <%= link_to "Add Customer", new_customer_path %>
</button>
<button>Go Back to..?</button>

<table>
  <tr>
    <th>Name</th>
    <th>Table #</th>
    <th>Bill Amount</th>
    <th></th>
    <th></th>
  </tr>

  <% @customers.each do |customer|%>
    <tr>
      <td><%= customer.name %></td>
      <td><%= customer.party_id %></td>
      <td><%= customer.total %></td>
      <td><%= link_to 'View', customer_path(customer) %></td>
      <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
    </tr>
  <%end%>
</table>


<!-- 
<div class="customer">
  <h2><strong><%= customer.name %></strong></h2>
  <h5><strong>Table #<%= customer.party_id %></strong></h5>
  <h5><strong>Bill Amount: $<%= customer.total %></strong></h5>
  
  <div class="customer-orders">
    Display all customer's orders from this tableNum(party_id)
  </div>

  <%= link_to 'View', customer_path(customer) %>
  <%= link_to 'Edit', edit_customer_path(customer) %>
</div> -->

RESTurant/app/views/customers/show.html.erb
<!-- Shows Customer Profile -->
<div class="customer">
  <h1><strong><%= @customer.name %></strong></h1>
  <h4><strong>Bill Total: $<%= @customer.total %></strong></h4><br>
      
  <%= link_to 'Go Back', party_path %>

  <div><br>
    <table>
      <tr colspan="4"><strong>Food Orders</strong></tr>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Total</th>
        <th></th>
      </tr>
      <%= render @orders %>
    </table>
  </div>

</div>