RESTurant/config/routes.rb
Rails.application.routes.draw do

  root to: 'users#login'
  resources :users, only: [:new, :create, :show, :destroy]
  resources :parties
  resources :customers 
  resources :orders
  resources :foods

  get 'sessions/new' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  delete 'sessions' => 'sessions#destroy'
  get 'login' => 'users#login'

end

RESTurant/app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :food
  belongs_to :customer

  validates :customer_id, :food_id, presence: true
  # after_create :update_total        # used to update order total after adding an order

  def update_total
    # how to update order total after adding an order???
  end

  # add 1 to quantity 
  def plus_order
  end

  # subtract 1 to quantity
  def minus_order
  end

end

RESTurant/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate

  def index
    @orders = Order.all
  end
  
  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end
  
  def edit
    @order = Order.find(params[:id])
  end

  def create
    @order = Order.create(order_params)

    if @order.save
      redirect_to order_path(@order)            # "order#show" profile view    redirect_to @order ??
    else 
      render 'new'      # otherwise, go back to new form
    end
  end
  
  def update
    @order = Order.find(params[:id])

    if @order.update(order_params)
      redirect_to order_path(@order)            # "order#show" profile view    redirect_to @order ??
    else
      render 'edit'     # otherwise, go back to edit form
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to orders_path                  # "orders#index" list of all orders view
  end

  private   # strong params
  def order_params
    params.require(:order).permit(:customer_id, :food_id, :quantity)     # include :total ???
  end

end

RESTurant/app/views/orders/_form.html.erb
<!-- EDIT:  <%= form_for :order, url: order_path(@order), method: :patch do |f| %> -->
<%= form_for @order do |f| %>

  <% food_array = Food.all.map{ |food| [food.name, food.id] } %>
  <%= options_for_select(food_array) %>

  <%= f.submit %><br>
<% end %>

RESTurant/app/views/orders/_order.html.erb
<!-- Shows each food and order in a table row -->
<tr>
  <td><%= @foods[order[:id]-1].name %></td>
  <td>$<%= @foods[order[:id]-1].price %></td>
  <td><%= order.quantity %></td>
  <td>$<%= order.total %></td>
  <!-- Edit order quantity?? -->
  <td><%= link_to 'Delete', order_path(order),
          method: :delete, 
          data: {confirm: 'Are you sure you want to delete this order?'} %></td>
</tr>


<!-- How to update & display order total cost? (quantity*price) -->
<!-- How to update & display customer total cost? (sum of all order totals) -->

RESTurant/app/views/orders/edit.html.erb
<div class="form">
  <h1>Edit Order Info</h1>
  <%= render partial: 'form' %>
</div>

RESTurant/app/views/orders/index.html.erb
<button>
  <%= link_to "Add Order", new_order_path %>
</button>
<button>Go Back to..?</button>

<table>
  <tr>
    <th>Customer_id</th>
    <th>Food_id</th>
    <th>Quantity</th>
    <th>Total Cost</th>
    <th></th>
    <th></th>
  </tr>

  <% @orders.each do |order|%>
    <tr>
      <td><%= order.customer_id %></td>
      <td><%= order.food_id %></td>
      <td><%= order.quantity %></td>
      <td><%= order.total %></td>
      <td><%= link_to 'Edit', edit_order_path(order) %></td>
      <td><%= link_to 'Delete', order_path(order),
              method: :delete, 
              data {confirm: 'Are you sure you want to delete this order?'} %></td>
    </tr>
  <% end %>
</table>


<!-- 
<div class="order">
  <h2><strong>Customer ID: <%= order.customer_id %></strong></h2>
  <h5><strong>Food ID: <%= order.food_id %></strong></h5>
  <h5><strong>Bill Amount: $<%= order.total %></strong></h5>

  <%= link_to 'Edit', edit_order_path(order) %>
  <%= link_to 'Delete', order_path(order),
              method: :delete, 
              data {confirm: 'Are you sure you want to delete this order?'} %>
</div> -->

RESTurant/app/views/orders/new.html.erb
<div class="form">
  <h1>Enter New Order!</h1>
  <%= render partial: 'form' %>
</div>

RESTurant/app/views/orders/show.html.erb
<!-- Shows Order Profile - Food Info -->
<div class="order">
  <h1><strong><%= @order.name %></strong></h1>
  <h4><strong>Bill Total: $<%= @order.total %></strong></h4><br>
      
  <%= link_to 'Go Back', party_path %>

  <div><br>
    <table>
      <tr colspan="4"><strong>Order Bill</strong></tr>
      <tr>
        <th>Name</th>
        <th>Jbdajsbfjas</th>
        <th>Quantity</th>
        <th>Total</th>
        <th></th>
      </tr>
      <%= render @orders %>
      <%= render @foods %>
    </table>
  </div>

</div>