RESTurant/config/routes.rb
Rails.application.routes.draw do

  root to: 'users#login'
  resources :users, only: [:new, :create, :show, :destroy]
  resources :parties
  resources :customers 
  resources :orders
  resources :foods

  get 'sessions/new' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  delete 'sessions' => 'sessions#destroy'
  get 'login' => 'users#login'

end

RESTurant/app/models/user.rb
class User < ActiveRecord::Base
  has_many :parties

  validates :username, presence: true, uniqueness: true
  has_secure_password   # Rails User Auth!
  
end

RESTurant/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate, except: [:new, :login, :create]
  # new user sign up form
  def new 
    @user = User.new
  end

  def login
    render file: 'users/login'
  end

  def show
    if (@user = User.find(params[:id]))            # GET /users/:id
      @parties = @user.parties.all
# render plain: @parties.inspect
    else
      render file: 'public/404', status: 404, formats: [html]
    end
  end

  def create
    # binding.pry
    render plain: params[:user].inspect
    @user = User.new(user_params)
    if @user.save
      session[:current_user_id] = @user.id 
      # redirect_to user_path(@user)            # GET /users/:id
    else
      redirect_to new_user_path(@user)        # GET /users/new for @user obj
    end
  end

  def destroy
    @user = User.find(params[:id])
    session[:current_user_id] = nil           
    @user.destroy
    redirect_to root_path                     # GET / -> /users/new
  end

  private
  # strong_params
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

RESTurant/app/views/users/login.html.erb
<div class="form">

  <h1>Log In here</h1>
  <% #TODO what's a form_tag for %>
  <%= form_for(:session, url:login_path) do |f| %>
    <%= f.label :username %><br>
    <%= f.text_field :username %><br>

    <%= f.label :password %><br>
    <%= f.password_field :password %><br>
    <br>

    <%= f.submit "Login"%>
  <% end %>
  <p>New user? <%= link_to "Sign up now!", new_user_path %></p>

</div>

RESTurant/app/views/users/new.html.erb
<div class="form">
  <h1>Sign Up here</h1>

  <!-- Rails Form helper -->
  <!-- form_for used for PUT & POST -->
  <%= form_for @user do |f| %>
    <%= f.label :username %><br>
    <%= f.text_field :username %><br>
    <%= f.label :password %><br>
    <%= f.password_field :password %><br>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %><br>
    <br>
    <%= f.submit "Sign Up" %><br>
  <% end %>
  <p>Already a member? <%= link_to "Log in here!", login_path %></p>
</div>

RESTurant/app/views/users/show.html.erb
<div id="user-page">
  <h1>Welcome back, <%= @user.username %>!</h1>
  <%= link_to 'Create New Party', new_party_path %>

  <!-- Display list of parties -->
  <br><br>
  <div id="parties">
    <table>
      <tr>
        <th>Table Num</th>
        <th>Did they pay yet?</th>
        <th>Bill Total</th>
        <th></th>   <!-- View -->
        <th></th>   <!-- Delete -->
      </tr>
      <%= render @parties %> 
    </table>
  </div>
  
  
  <br><br><br>
  <button>    <!-- make this red -->
    <%=button_to 'DELETE Account', @user, :method => :delete %>
  </button>
</div>