RESTurant/config/routes.rb
Rails.application.routes.draw do

  root to: 'users#login'
  resources :users, only: [:new, :create, :show, :destroy]
  resources :parties
  resources :customers 
  resources :orders
  resources :foods

  get 'sessions/new' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  delete 'sessions' => 'sessions#destroy'
  get 'login' => 'users#login'

end

RESTurant/app/models/food.rb
class Food < ActiveRecord::Base
  has_many :orders
  has_many :customers, :through => :orders      # NECESSARY ??

  validates :name, presence: true, uniqueness: true
  validates :cuisine, presence: { message: "Where did this dish originate from?" }
  validates :price, numericality: true, presence: { message: "This dish cant be free" }
  validates :allergins, presence: { message: "Are you sure? We dont want anyone getting sick!" }
  validates :description, presence: { message: "Cmon, what's in it? Or at least give us a fun fact about this dish!" }

end

RESTurant/app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate

  def index
    @foods = Food.all
  end
  
  def show
    @food = Food.find(params[:id])
  end

  def new
    @food = Food.new
  end
  
  def edit
    @food = Food.find(params[:id])
  end

  def create
    @food = Food.create(food_params)

    if @food.save
      redirect_to food_path(@food)            # "food#show" profile view    redirect_to @food ??
    else 
      render 'new'      # otherwise, go back to new form
    end
  end
  
  def update
    @food = Food.find(params[:id])

    if @food.update(food_params)
      redirect_to food_path(@food)            # "food#show" profile view    redirect_to @food ??
    else
      render 'edit'     # otherwise, go back to edit form
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_path                  # "foods#index" list of all foods view
  end

  private   # strong params
  def food_params
    params.require(:food).permit(:name, :cuisine, :price, :allergins, :description)
  end

end

RESTurant/app/views/foods/_food.html.erb
<div class="single-food">
  <h1> <%= food.name %> <div>$<%= food.price %></div></h1>
  <h3><strong>Cuisine: </strong><%= food.cuisine %> </h3>
  <div> 
    <p><strong>Allergins: </strong><%= food.allergins %></p> 
    <p><strong>Description: </strong><%= food.description %></p>
  </div>
  <%= link_to 'Edit', edit_food_path(@food) %>    <!-- Edit food form -->
  <%= link_to 'Go Back', foods_path %>            <!-- List of all foods -->
</div>

RESTurant/app/views/foods/_form.html.erb
<!-- EDIT:  <%= form_for :food, url: food_path(@food), method: :patch do |f| %> -->
<%= form_for @food do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br><br>

  <%= f.label :cuisine %><br>
  <%= f.text_field :cuisine %><br><br>

  <%= f.label :price %><br>
  <%= f.number_field :price %><br><br>

  <%= f.label :allergins %><br>
  <%= f.text_field :allergins %><br><br>

  <%= f.label :description %><br>
  <%= f.text_field :description %><br><br>

  <%= f.submit %><br>
<% end %>

RESTurant/app/views/foods/edit.html.erb
<div class="form">
  <h1>Edit Food Info</h1>
  <%= render partial: 'form' %>
</div>

RESTurant/app/views/foods/index.html.erb
<button>
  <%= link_to "Add New Food", new_food_path %>
</button>
<button>Go Back to..?</button>

<table>
  <tr>
    <th>Name</th>
    <th>Cuisine</th>
    <th>Price</th>
    <th>Allergins</th>
    <th>Description</th>
    <th></th>
    <th></th>
  </tr>

  <% @foods.each do |food|%>
    <tr>
      <td><%= food.name %></td>
      <td><%= food.cuisine %></td>
      <td><%= food.price %></td>
      <td><%= food.allergins %></td>
      <td><%= food.description %></td>
      <td><%= link_to 'View', food_path(food) %></td>
      <td><%= link_to 'Edit', edit_food_path(food) %></td>
    </tr>
  <%end%>
</table>

<!--   <div class="food">
    <div class="food_info">
      <%= food.name %>
      <span class="price"> $<%= food.price%> </span>
      <%= food.cuisine %>
      <%= food.allergins %>
    </div>
    <div class="description">
      <%= food.description %>
    </div>
    <%= link_to 'Edit', edit_food_path %>
  </div> -->

RESTurant/app/views/foods/new.html.erb
new.html.erb

RESTurant/app/views/foods/show.html.erb
<!-- does this render each food correctly?? -->
<%= render partial: 'food' %>